### ISSUE TITLE
Mongodb Exporter doesn't Show the Metrics Using Docker and Prometheus

### ISSUE THREAD

**Issue by mostafaghadimi** [dcu/mongodb_exporter#117]
I'm trying to dockerize mongodb monitoring from the tutorial I have seen in [this page](https://medium.com/@journald/prometheus-on-ecs-with-mongodb-exporter-8b58dad1ee8f).

Here is my Dockerfile configuration:

    FROM alpine
    RUN apk update && apk add wget && rm -rf /var/cache/apk/*
    RUN wget https://github.com/dcu/mongodb_exporter/releases/download/v1.0.0/mongodb_exporter-linux-amd64
    RUN chmod 777 mongodb_exporter-linux-amd64
    EXPOSE 9001

Prometheus.yml:

    global:
        scrape_interval: 15s
        external_labels:
            monitor: 'my-monitor'
    scrape_configs:
        - job_name: 'mongodb-exporter'
          static_configs:
              - targets: ['mongodb-exporter:9001']

docker-compose.yml:

    version: '3'
    
    services: 
      mongo:
        image: mongo
        container_name: mongo
        restart: always
        environment: 
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    
      prometheus:
        image: prom/prometheus
        restart: always
        ports:
          - 9090:9090
        volumes:
          - /home/mostafa/Desktop/docker_lab/mongo/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command: 
          - '--config.file=/etc/prometheus/prometheus.yml'
    
      mongodb-exporter:
        build: .
        command: ./mongodb_exporter-linux-amd64 -logtostderr -mongodb.uri mongodb://root:example@mongo:27017 -groups.enabled 'asserts,durability,background_flusshing,connections,extra_info,global_lock,index_counters,network,op_counters,op_counters_repl,memory,locks,metrics'
        restart: always
        ports: 
          - 9001:9001

> 1 mongodb_collector.go:70] Collecting Oplog Status

> 1 oplog_status.go:127] Failed to get local.oplog_rs collection stats.

The metrics I should see is [this][1] but now I just see the following metrics.

[![My Metrics][2]][2]

  [1]: https://miro.medium.com/max/700/1*H0l126osHJkqbC-2pCDfyw.png
  [2]: https://i.stack.imgur.com/u5Hbb.png

**Comment by avishefi** [comment]
Try using: `-mongodb.uri mongodb://root:example@mongo:27017`

**Comment by mostafaghadimi** [comment]
@avishefi  sorry I have edited the post. It doesn't work even with mongo:27017

**Comment by GFZRZK** [comment]
> Try using: `-mongodb.uri mongodb://root:example@mongo:27017`

Is there any difference between your mongouri and the auther's?

**Comment by pauldintel** [comment]
@mostafaghadimi  - have you been able to make this work . ! I still have issue not getting full spectrum of mongo metrics through exporter .

**Comment by mostafaghadimi** [comment]
@pauldintel Yes, I did. Please share the details about how you deploy your applications. In case of using Docker, there might be network related issues.

**Comment by pauldintel** [comment]
hi @mostafaghadimi  thanks for offering the help . I am using mongo7.0.5, prometheus , nodeexporter , grafana and mongodb exporter in docker container (all inside same network bridge) . 
Below is the docker specification : 

  mongodb-exporter:
    hostname: mongodb-exporter
    container_name: mongodb-exporter
    image: mongoexport:prom
    command: ./mongodb_exporter-linux-amd64 -logtostderr -mongodb.uri mongodb://admin1:password@mongo1:27017/mydb -groups.enabled 'asserts,durability,background_flusshing,connections,extra_info,global_lock,index_counters,network,op_counters,op_counters_repl,memory,locks,metrics'
    restart: always
    ports:
      - 9001:9001
    networks:
      mongo_network:

Please note above mongo1 is the container name and mydb is the db name . the exporter linux utility is used in command line. 
the issue with the above is I am getting Authentication failed error : the prometheus portal shows mongo exporter is up and  running on 9001 port and no issue . But just shows couple of http# metrics and nothing on mongo metrics shown . So my gut feeling is this is because mongo authentication failure. 

![image](https://github.com/dcu/mongodb_exporter/assets/104393458/eb82cef7-c145-45f9-843e-8779badc4495)

Generally at this moment my thought is those user/password needs to be preexisting on the database. Once I create them in database with admin roles I started getting Panic error plus mongo exporter shows down in prometheus .. 

![image](https://github.com/dcu/mongodb_exporter/assets/104393458/4ba57691-b49a-42b2-99cf-4b44d9756c7c)

So at this moment it is being very strange ! I want to use Grafana dashboard comes pre-shipped with mongo metrics that works on exporter and stuck on implementing that solution.

**Comment by mostafaghadimi** [comment]
@pauldintel you're welcome. I think you can create user with environment variables and would you please also share your mongodb service in docker-compose file details?

**Comment by avishefi** [comment]
@pauldintel take a look if this is relevant: https://github.com/dcu/mongodb_exporter/issues/110

I had the same message: `panic: runtime error: invalid memory address or nil pointer dereference`

I patched according to [this comment](https://github.com/dcu/mongodb_exporter/issues/110#issuecomment-483251335) and it worked.
