### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by baseio** [dcu/mongodb_exporter#4]
Hi,

Build fails with
```
~/Prometheus/mongo_exporter/src/github.com/dcu/mongodb_exporter$ make build
go get -u github.com/prometheus/client_golang/prometheus
# github.com/prometheus/common/model
../../prometheus/common/model/signature.go:33:17: error: reference to undefined identifier ‘sync.Pool’
  hashAndBufPool sync.Pool
                 ^
make: *** [deps] Error 2
```

ideas?

(still on Mongo 2.4)

**Comment by dcu** [comment]
hi @baseio what's your golang version?

    $ go version

**Comment by baseio** [comment]
go version go1.3 darwin/amd64

**Comment by baseio** [comment]
sorry - on the server `go version` reports
`go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64`

**Comment by dcu** [comment]
looks like it's gccgo, please try compiling with the official golang

**Comment by bugcy013** [comment]
@dcu  I am also facing building issue

➜  mongodb_exporter git:(master) go version
go version go1.5.1 linux/amd64

➜  mongodb_exporter git:(master) make build         
go get -u github.com/prometheus/client_golang/prometheus
go get -u gopkg.in/yaml.v2
go get -u github.com/jteeuwen/go-bindata
go get -u gopkg.in/mgo.v2
go-bindata -pkg=shared -o=shared/assets.go groups.yml
go build mongodb_exporter.go
mongodb_exporter.go:6:2: cannot find package "github.com/dcu/mongodb_exporter/collector" in any of:
	/home/dhanasekaran/app_packages/go/src/github.com/dcu/mongodb_exporter/collector (from $GOROOT)
	/home/dhanasekaran/app_packages/go/src/src/github.com/dcu/mongodb_exporter/collector (from $GOPATH)
mongodb_exporter.go:7:2: cannot find package "github.com/dcu/mongodb_exporter/shared" in any of:
	/home/dhanasekaran/app_packages/go/src/github.com/dcu/mongodb_exporter/shared (from $GOROOT)
	/home/dhanasekaran/app_packages/go/src/src/github.com/dcu/mongodb_exporter/shared (from $GOPATH)
make: *** [build] Error 1

Environmental variables:
export GOROOT=/home/dhanasekaran/app_packages/go
export GOPATH=$GOROOT/src
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

Note :: I am new to go lang, I did any mistake in environmental variables

can you please guide me. How to fix this.

**Comment by dcu** [comment]
@bugcy013 that's weird. did you use `git clone` instead of `go get` to install the package?

try 

    go get github.com/dcu/mongodb_exporter
    cd $GOPATH/src/github.com/dcu/mongodb_exporter
    make build

**Comment by dhanasekaran-anbalagan** [comment]
@dcu  Thanks, You are correct, I did git clone instead of go get

it's working.

➜  ~  rm -rf mongodb_exporter 
➜  ~  go get github.com/dcu/mongodb_exporter

➜  ~  
➜  ~  cd $GOPATH/src/github.com/dcu/mongodb_exporter
➜  mongodb_exporter git:(master) make build
go get -u github.com/prometheus/client_golang/prometheus
go get -u gopkg.in/yaml.v2
go get -u github.com/jteeuwen/go-bindata
go get -u gopkg.in/mgo.v2
go-bindata -pkg=shared -o=shared/assets.go groups.yml
go build mongodb_exporter.go
➜  mongodb_exporter git:(master) ✗ ls
collector  Dockerfile  groups.yml  LICENSE  Makefile  mongodb_exporter  mongodb_exporter.go  README.md  screenshots  shared
➜  mongodb_exporter git:(master) ✗ 

thanks much. now I can play with mongodb_exporter
